DROP DATABASE IF EXISTS DIDACTIC;
CREATE DATABASE DIDACTIC;
USE DIDACTIC;

CREATE TABLE Usuarios(
	Id_Usuario INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Username VARCHAR(100) NOT NULL,
	Apellidos VARCHAR(100) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	Clave VARCHAR(100) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Localidad VARCHAR(100) NOT NULL,
	Postal VARCHAR(100) NOT NULL,
	Pais VARCHAR(100) NOT NULL,
	Telefono VARCHAR(100) NOT NULL,
	Fecha_reg VARCHAR(100) NOT NULL
);

CREATE TABLE Productos(
	Id_Producto INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Categoria VARCHAR(100) NOT NULL,
	Producto VARCHAR(100) NOT NULL,
	Marca VARCHAR(100) NOT NULL,
	Precio VARCHAR(100) NOT NULL,
	Existencia VARCHAR(100) NOT NULL
);

CREATE TABLE Pedidos(
	Id_Pedido INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Username VARCHAR(100) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	Telefono VARCHAR(100) NOT NULL,
	PRODUCTO VARCHAR(100) NOT NULL,
	CANTIDAD VARCHAR(100) NOT NULL,
	Postal VARCHAR(100) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Fecha_reg VARCHAR(100) NOT NULL
);

CREATE TABLE Empleados(
	Id_Empleado INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(100) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	Telefono VARCHAR(100) NOT NULL,
	Postal VARCHAR(100) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Clave VARCHAR(100) NOT NULL
);

CREATE TABLE Ventas(
	Id_Venta INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Total VARCHAR(100) NOT NULL,
	Username VARCHAR(100) NOT NULL,
	Fecha_reg VARCHAR(100) NOT NULL
);




INSERT INTO Productos VALUES('1','OFICINA','BORRADOR','ERASER','$65.68','84');
INSERT INTO Productos VALUES('2','OFICINA','LAMPARA','LUMINIC','$455.99','24');
INSERT INTO Productos VALUES('3','OFICINA','ECRITORIO','SOL','$2499.99','58');
INSERT INTO Productos VALUES('4','OFICINA','PERFORADORA','NORMA','$45.36','32');
INSERT INTO Productos VALUES('5','DIDACTICO','TIJERAS','ROM','$15.63','51');
INSERT INTO Productos VALUES('6','DIDACTICO','MARCADOR','SHARPIE','$18.36','35');
INSERT INTO Productos VALUES('7','DIDACTICO','PEGAMENTO','NORMA','$12.87','41');
INSERT INTO Productos VALUES('8','DIDACTICO','LIBRETA(P)','NORMA','$87.56','87');
INSERT INTO Productos VALUES('9','PRODUCTO','COSEDORA','SIC','$364.98','68');
INSERT INTO Productos VALUES('10','PRODUCTO','CINTA','PEGI','$25.99','14');
INSERT INTO Productos VALUES('11','PRODUCTO','ENGRAPADORA','SMART','$79.36','18');
INSERT INTO Productos VALUES('12','PRODUCTO','BROCHES','BACO','$12.00','125');